# Copyright (c) 2015-2016 Alireza Kheirkhahan
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)
#
---

#- name: create slurm group
#  group: name=slurm gid=64030 state=present

- name: create wash user
  user: name=wash comment='Bryce Adelstein-Lelbach' uid=1000 shell=/bin/bash createhome=no

- name: create hkaiser user
  user: name=hkaiser comment='Hartmut Kaiser' uid=1001 groups=wheel shell=/bin/bash createhome=no

- name: create twright user
  user: name=twright comment='Tim Wright' uid=1002 groups=wheel shell=/bin/bash createhome=no

- name: create hapoo user
  user: name=hapoo comment='Alireza Kheirkhahan' uid=1007 groups=wheel shell=/bin/bash createhome=no


