# Copyright (c) 2015-2016 Alireza Kheirkhahan
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)
#
---
- name: mount the nfs file system
  mount: name=/pkg src=otter:/tools/pkg  fstype=nfs state=mounted

- name: install login node packages
  yum: name={{ item }} state=installed
  with_items:
    - firefox
    - icedtea-web
    - screen

- name: install google chrome
  yum: name={{ item }} state=installed
  with_items:
    - /pkg/google-chrome-stable_current_x86_64.rpm

- name: unmount the temporary file system
  mount: name=/pkg/ src=otter:/tools/pkg  fstype=nfs state=unmounted

- name: remove temporary file system from fstab in case Ansible made it permanent
  mount: name=/pkg/ src=otter:/tools/pkg  fstype=nfs state=absent

- name: copy ssh_host_ecdsa_key
  copy: src=/tools/login_key/ssh_host_ecdsa_key dest=/etc/ssh/ssh_host_ecdsa_key owner=root group=ssh_keys mode=640

- name: copy ssh_host_ecdsa_key.pub
  copy: src=/tools/login_key/ssh_host_ecdsa_key.pub dest=/etc/ssh/ssh_host_ecdsa_key.pub owner=root group=root mode=644

- name: copy ssh_host_ed25519_key
  copy: src=/tools/login_key/ssh_host_ed25519_key dest=/etc/ssh/ssh_host_ed25519_key owner=root group=ssh_keys mode=640

- name: copy ssh_host_ed25519_key.pub
  copy: src=/tools/login_key/ssh_host_ed25519_key.pub dest=/etc/ssh/ssh_host_ed25519_key.pub owner=root group=root mode=644

- name: copy ssh_host_rsa_key
  copy: src=/tools/login_key/ssh_host_rsa_key dest=/etc/ssh/ssh_host_rsa_key owner=root group=ssh_keys mode=640

- name: copy ssh_host_rsa_key.pub
  copy: src=/tools/login_key/ssh_host_rsa_key.pub dest=/etc/ssh/ssh_host_rsa_key.pub owner=root group=root mode=644
