# Copyright (c) 2015-2016 Alireza Kheirkhahan
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)
#
---
- name: mount the nfs file system
  mount: name=/pkg/ src=otter:/tools/pkg  fstype=nfs state=mounted

- name: install slurm dependencies
  yum: name={{ item }} state=installed
  with_items:
    - openssl-devel
    - pam-devel
    - readline-devel
    - perl-ExtUtils-MakeMaker
    - perl-Switch
    - redhat-lsb
    - hwloc
    - hwloc-devel 
    - ncurses-devel
    - ncurses 
    - perl-DBI

- name: install slurm packages
  yum: name={{ item }} state=installed
  with_items:
    - /pkg/slurm/17.02.1-2/slurm-17.02.1-2.el7.centos.x86_64.rpm
    - /pkg/slurm/17.02.1-2/slurm-plugins-17.02.1-2.el7.centos.x86_64.rpm
    - /pkg/slurm/17.02.1-2/slurm-munge-17.02.1-2.el7.centos.x86_64.rpm
    - /pkg/slurm/17.02.1-2/slurm-pam_slurm-17.02.1-2.el7.centos.x86_64.rpm

- name: unmount the temporary file system
  mount: name=/pkg/ src=otter:/tools/pkg  fstype=nfs state=unmounted

- name: remove temporary file system from fstab in case Ansible made it permanent
  mount: name=/pkg/ src=otter:/tools/pkg  fstype=nfs state=absent

- name: create slurm group
  group: name=slurm gid=64030 state=present

- name: create slurm user
  user: name=slurm comment='Slurm Service' uid=64030 group=slurm shell=/sbin/nologin home=/var/lib/slurm createhome=no

- name: Create log folder for Slurm's services
  file: path=/var/log/slurm state=directory owner=slurm group=slurm

- name: Create slurm home folder for running batch jobs
  file: path=/var/lib/slurm state=directory owner=slurm group=slurm mode=755

- name: Copy config file to the target node
  copy: src=/etc/slurm/slurm.conf dest=/etc/slurm/slurm.conf

- name: Copy Slurm PAM config file
  copy: src=/tools/rostam/config/slurm.pam dest=/etc/pam.d/slurm

# /etc/init.d/slurm is on by defulat. It  will start slurmd on compute nodes
# But we want to run systemd service slurmd instead.
# This makes sure the locked memory is set for infiband/mpi library.

# Slurm 17 no longer creates SysV service
# So first disable SysV service to make sure slurm is off on chkconfig --list
#- name: Disable slurm SysV service on compute node
#  service: name=slurm enabled=no

# Enable slurmd systemd service on compute node
- name: Enable slurmd systemd service on compute node
  systemd: name=slurmd enabled=yes

