# Copyright (c) 2015-2016 Alireza Kheirkhahan
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Moved installation to easybuild, now easybuild will install the intel compiler.
# We needed this if we want to install intel drivers or services such as Vtune.
---

- name: install some library packages
  yum: name={{ item }} state=installed
  with_items:
    - glibc-devel.i686
    - libstdc++-devel.i686
    - libgcc.i686

- name: Create folder for intel lisense
  file: path=/opt/intel/licenses/ state=directory

- name: rsync intel licenses
  synchronize: src=/opt/intel/licenses/ dest=/opt/intel/licenses/ delete=yes

