# Copyright (c) 2015-2016 Alireza Kheirkhahan
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)
#
---
- name: install munge
  yum: name=munge,munge-devel state=latest

- name: copy munge.key
  copy: src=/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=400

- name: start munge service
  service: name=munge.service enabled=yes state=started
